### ISSUE TITLE
Unable to access to the defined routes

### ISSUE THREAD

**Issue by Hetarnam** [cristian-g/vsf-odoo#26]
Hello,

I installed the module on my local odoo installation, everything is good, but when I try to access some routes defined in `controllers/public.py` I just have a 404, the same when I use Vue storefront, when it try to call the API.

I missed something during the installation?

Thank you in advance.

**Comment by cristian-g** [comment]
Hello,

How is your local Odoo installation configured? How do you access to the Odoo website? Are you using the default http://localhost:8069, right?

Then, for instance, this route should work for retrieving a JSON list of products (just visit it by using your web browser, it should work since it is a GET request):
http://localhost:8069/api/catalog/vue_storefront_catalog/product/_search?_source_exclude=description%2Csgn%2C%2A.sgn%2Cmsrp_display_actual_price_type%2C%2A.msrp_display_actual_price_type%2Crequired_options&_source_include=type_id%2Csku%2Cname%2Ctax_class_id%2Cspecial_price%2Cspecial_to_date%2Cspecial_from_date%2Cprice%2CpriceInclTax%2CoriginalPriceInclTax%2CoriginalPrice%2CspecialPriceInclTax%2Cid%2Cimage%2Csale%2Cnew%2Cconfigurable_children.image%2Cconfigurable_children.sku%2Cconfigurable_children.price%2Cconfigurable_children.special_price%2Cconfigurable_children.priceInclTax%2Cconfigurable_children.specialPriceInclTax%2Cconfigurable_children.originalPrice%2Cconfigurable_children.originalPriceInclTax%2Cconfigurable_children.color%2Cconfigurable_children.size%2Cconfigurable_children.id%2Cconfigurable_children.tier_prices%2Cproduct_links%2Curl_path%2Curl_key%2Cstatus%2Ctier_prices&from=0&size=50&sort=updated_at%3Adesc

**Comment by Hetarnam** [comment]
It's a basic local installation, fresh one created yesterday, I just installed "Inventory" and "Contact" modules in addition to your one.

Yep my url is http://localhost:8069, but if I click on your link it gives me a 404 again :/

I restarted my odoo server multiple times to be sure.

**Comment by cristian-g** [comment]
Which Odoo version are you using? Version 12, right?

I have the following modules installed: Website, eCommerce, Inventory, Purchase, Sales, Point of Sale

In order to restart the server I use `net stop odoo-server-12.0 && net start odoo-server-12.0`, try it too.

**Comment by Hetarnam** [comment]
Yes Odoo 12, and btw I'm on linux.

I installed the same modules as you, but still nothing...

Maybe I'm missing something somewhere, but nothing appear in the logs, or somewhere else...

**Comment by cristian-g** [comment]
I haven't tested the module on Linux yet, just on Windows. It should work on Linux too because in theory routes are registered in the same way but I'm not 100% sure right now.
I hope to find some time soon in order to try it on Linux but if you discover something (logs or something) please let me know and I'll try to help!

**Comment by Hetarnam** [comment]
Ok I found the problem, you left the import of `odoo.addons.restful` instead of `odoo.addons.vue_storefront` and also some `restful.expire...`. After replacing all of them by `vue_storefront` everything worked!
