### ISSUE TITLE
Odoo v13

### ISSUE THREAD

**Issue by daolvcntt** [cristian-g/vsf-odoo#29]
This addon compatible with Odoo ver. 13 in the future?

**Comment by codeagencybe** [comment]
Any update, ETA, ... on this? 
I'm also looking forward to v13

**Comment by cristian-g** [comment]
Hello,

I must be honest here, with my work as a developer and while studying a masters degree, I'm very limited in available time to update this module to Odoo v13.

I can't say any ETA on my end... Sorry!

Of course, contributions are welcome. I don't know if v13 is so much different than v12, so you can consider to make a pull request. Thanks!

**Comment by codeagencybe** [comment]
Hello @cristian-g 

Do you have any update or feedback yet? 
I know you were busy, but perhaps you still found some time to work on it. 
As fas I know, Odoo 13 is not too much different from v12. There seems to be some changes mostly on the api.multi part that needs rewriting. 
I'm not an Odoo or Python developer myself, otherwise I would have jumped on it straight away and help you out. But unfortunately I'm not. 

Is there anything else I can do to help on the project?
